#Docker Compose for development
version: '3.8'
services:
    prodz-website:
        image: prodz-website:1.0
        user: '1000:1000'
        environment:
            PORT: 3000
        restart: always
        container_name: prodz-website
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - type: bind
              source: .
              target: /app
        ports:
            - 3000:3000
